//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onyx_Client_UI.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("onyx_Client_UI.Resources.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASSIGNED TO YOU.
        /// </summary>
        public static string Assignedtoyou {
            get {
                return ResourceManager.GetString("Assignedtoyou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar.
        /// </summary>
        public static string Bar {
            get {
                return ResourceManager.GetString("Bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIND.
        /// </summary>
        public static string Bind {
            get {
                return ResourceManager.GetString("Bind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR CARD IS NOW CHARGED $ 1 TO CHECK THE CORRECT BINDING OF THE CARD.
        /// </summary>
        public static string Cardcorrectbinding {
            get {
                return ResourceManager.GetString("Cardcorrectbinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number.
        /// </summary>
        public static string Cardnumber {
            get {
                return ResourceManager.GetString("Cardnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCV.
        /// </summary>
        public static string CCV {
            get {
                return ResourceManager.GetString("CCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose security password.
        /// </summary>
        public static string Choosesecuritypassword {
            get {
                return ResourceManager.GetString("Choosesecuritypassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLOSE.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONGRATULATIONS ON SUCCESSFUL REGISTRATION.
        /// </summary>
        public static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cybershoke.
        /// </summary>
        public static string Cybershoke {
            get {
                return ResourceManager.GetString("Cybershoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t forget it!.
        /// </summary>
        public static string Don_tforgetit {
            get {
                return ResourceManager.GetString("Don\'tforgetit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not tell anyone your personal data!.
        /// </summary>
        public static string Donottellanyoneyourpersonaldata {
            get {
                return ResourceManager.GetString("Donottellanyoneyourpersonaldata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string Games {
            get {
                return ResourceManager.GetString("Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello!.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holder name.
        /// </summary>
        public static string Holdername {
            get {
                return ResourceManager.GetString("Holdername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree with the personal data processing policy.
        /// </summary>
        public static string Iagreewiththepersonaldata {
            get {
                return ResourceManager.GetString("Iagreewiththepersonaldata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree with the rules of visiting the club complex.
        /// </summary>
        public static string Iagreewiththerules {
            get {
                return ResourceManager.GetString("Iagreewiththerules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID number.
        /// </summary>
        public static string IDnumber {
            get {
                return ResourceManager.GetString("IDnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIN.
        /// </summary>
        public static string IIN {
            get {
                return ResourceManager.GetString("IIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last step!.
        /// </summary>
        public static string Laststep {
            get {
                return ResourceManager.GetString("Laststep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link your card.
        /// </summary>
        public static string Linkyourcard {
            get {
                return ResourceManager.GetString("Linkyourcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG IN.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle name.
        /// </summary>
        public static string Middlename {
            get {
                return ResourceManager.GetString("Middlename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEXT.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONYX.
        /// </summary>
        public static string ONYX {
            get {
                return ResourceManager.GetString("ONYX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation.
        /// </summary>
        public static string Passwordconfirmation {
            get {
                return ResourceManager.GetString("Passwordconfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string Phonenumber {
            get {
                return ResourceManager.GetString("Phonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promocode.
        /// </summary>
        public static string Promocode {
            get {
                return ResourceManager.GetString("Promocode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register to get started.
        /// </summary>
        public static string Registertogetstarted {
            get {
                return ResourceManager.GetString("Registertogetstarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTRATION.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation.
        /// </summary>
        public static string Reservation {
            get {
                return ResourceManager.GetString("Reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to continue.
        /// </summary>
        public static string Signintocontinue {
            get {
                return ResourceManager.GetString("Signintocontinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string Signup {
            get {
                return ResourceManager.GetString("Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft.
        /// </summary>
        public static string Soft {
            get {
                return ResourceManager.GetString("Soft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STANDART 75.
        /// </summary>
        public static string Standart75 {
            get {
                return ResourceManager.GetString("Standart75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome back!.
        /// </summary>
        public static string Welcomeback {
            get {
                return ResourceManager.GetString("Welcomeback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of birth.
        /// </summary>
        public static string Yearofbirth {
            get {
                return ResourceManager.GetString("Yearofbirth", resourceCulture);
            }
        }
    }
}
